name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove old cmake
      run: apt remove cmake
    - name: Fetch cmake 3.27.1 install script and put it into /opt/cmake
      run: curl -SL -o /opt/cmake.sh https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-linux-x86_64.sh 
    - name: Make the cmake install script executable
      run: chmod +x /opt/cmake.sh 
    - name: Install Cmake from the script
      run: /opt/cmake.sh --prefix=/usr/local/ --exclude-subdir
    - name: Create symlinks to the binaries 
      run: ln -s /opt/cmake*/bin/* /usr/local/bin/
    - uses: actions/checkout@v3
    - name: Build Debug
      run: cargo build --verbose
    - uses: actions/checkout@v3
    - name: Build Release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
