name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update Dependencies
      run: bash -c apt remove cmake && curl -SL -o /opt/cmake.sh https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-linux-x86_64.sh && cd /opt && chmod +x cmake.sh && yes | ./cmake.sh && ln -s /opt/cmake*/bin/* /usr/local/bin/"
    - uses: actions/checkout@v3
    - name: Build Debug
      run: cargo build --verbose
    - uses: actions/checkout@v3
    - name: Build Release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
